SYMBOL = "symbol"
PRICE = "price"
BUY_PRICE = "buy_price"
QUANTITY = "quantity"
SELL_PRICE_THRESHOLD = "selling_price_threshold"
TRIGGER_PRICE = "trigger_price"
TRIGGER = "trigger"
CUMULATIVE_QUANTITY = "cumulative_quantity"
ORDER_ID = "order_id"
SELL_PRICE = "sell_price"
SLTP = "sltp"

RANGE = "RANGE"
PRINCIPAL = "PRINCIPAL"
IRR = "IRR"
TRIGGER_LIMIT = "TRIGGER_LIMIT"
PRICE_DELTA = "PRICE_DELTA"